/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense, useRef } from 'react'

import { useGLTF,  } from '@react-three/drei'

export default function Door(props) {
  const gltf = useGLTF('/wooden_door/scene.gltf')
  return (
    <Suspense fallback={null}   >
      <primitive object={gltf.scene} {...props}/>
    </Suspense>
  )
}

useGLTF.preload('/wooden_door/scene.gltf')