/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/assets/nature/Fence_Middle.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube187.geometry} material={materials.Wood} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube187_1.geometry}
        material={materials.Wood_Light}
      />
    </group>
  )
}

useGLTF.preload('/assets/nature/Fence_Middle.gltf')
