/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/assets/nature/Tower.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube292.geometry}
        material={nodes.Cube292.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube292_1.geometry}
        material={nodes.Cube292_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube292_2.geometry}
        material={nodes.Cube292_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube292_3.geometry}
        material={materials.Tower}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube292_4.geometry}
        material={materials.Black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube292_5.geometry}
        material={materials.Metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube292_6.geometry}
        material={materials.Flag}
      />
      <group position={[1.25, 2.89, 3.16]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={nodes.Cylinder003.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={nodes.Cylinder003_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_2.geometry}
          material={nodes.Cylinder003_2.material}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/nature/Tower.gltf')



