/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from "@react-three/cannon";

export default function Model(props) {
  const [ref] = useBox(() => ({
    type: "Static",
    position: props.position,
    args: [1, 1, 1],
  }));

  //   const group = useRef()
  const { nodes, materials } = useGLTF("/assets/nature/Tree.gltf");
  return (
    <group ref={ref} {...props} dispose={null}
    >
      <mesh castShadow receiveShadow geometry={nodes.Cube118.geometry} material={materials.Wood} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube118_1.geometry}
        material={materials.Green}
      />
    </group>
  );
}

useGLTF.preload("/assets/nature/Tree.gltf");
